### PR TITLE
Refugee phrasebook/master

### PR DESCRIPTION
**Pull request by Michal-Koeckeis-Fresel**
some cleanups

### CODE REVIEW

**Comment by osg** [comment]
Does this mean that the other PR can be deleted without reviewing and merging it?

**Comment by osg** [comment]
Any TODO list or item ought to be handled via GitHub issues so that people can take on self-contained work, have others provide feedback about it, change it (without holding up other work), and get a thumbs up to merge it.

**Comment by Michal-Koeckeis-Fresel** [comment]
Del+Merge is ok

just pushed the last known good state - please use it as it’s easier to review

**Comment by Michal-Koeckeis-Fresel** [comment]
the current TODO in workspace/docs is a work-around as i do not have access rights to do these tasks

**Comment by osg** [comment]
I made a comment in the other PR for you to delete it.

**Comment by osg** [comment]
Ah, thanks for pointing that out.

**Comment by osg** [comment]
What does the `workplace` directory mean? Is it your personal workspace? If so, how about we rename it to something that matches its contents.

**Comment by Michal-Koeckeis-Fresel** [comment]
wanted to ask the same question - any ideas?

maybe scripted_pdf?

**Comment by osg** [comment]
Might be easier to come to that answer by writing a `README.md` file in `workplace` explaining the contents. The main thing that people usually leave out is the "What?" question. Some of these questions might prompt you to write up something:
http://infobits.eu/documentation/starting-point/

Refer to purpose, audience, scope, organization.

I am happy to pair with you on this because it will save a lot of time for those who want to collaborate on it and can get a quick overview of what it is.

**Comment by Michal-Koeckeis-Fresel** [comment]
closed all trees - will restart using new PR

Any ideas for naming the new dir?

**Pull request closed without merging**
