### PR TITLE
added files

### PR DESCRIPTION
**Pull request by Michal-Koeckeis-Fresel**
add exported data from book for reference and possibility to work with

### CODE REVIEW

**Comment by osg** [comment]
@michal-fre Thanks for the PR. Why would be check output files into source control? Also, there is a lot to look at for this PR so I'll need a bit of time.

**Comment by osg** [comment]
What does `workplace` mean? Does it mean that the phrases relate to the workplace?

**Comment by Michal-Koeckeis-Fresel** [comment]
Hi Ursula

it is a bunch of shell-scripts that 

# download the files

# do some text-work (cutting columns…)

# create tables for import in latex

# latex-template that creates a pdf-output

Dev is done on a Mac. It should run on any linux too.

The code is rather dirty - needs cleanup (hardcoding, no variables, …)

But it’s a first step to produce automated PDFs
Prerequisites are: 
running Linux or Mac
willing to install some tools (i.E. TeX Live 2015, …)
some experience in Terminal as for now the languages are hardcoded

Greeting

Michal

**Comment by osg** [comment]
@Glottotopia How much overlap is there here compared to what you are working on?

**Comment by Glottotopia** [comment]
On 09/16/2015 08:29 PM, Ursula Kallio wrote:

> @Glottotopia How much overlap is there here compared to what you are working on?

i started with Latex, but now I am on the web, so not too much overlap.
I can contribute to the latex code if necessary

**Comment by osg** [comment]
@michal-fre Please delete this PR.

**Pull request closed without merging**
